version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the pre_build phase...
      - sudo yum update
      - sudo yum install -y nginx
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /var/www/html      
  post_build:
    commands:
      - echo congiguring NGINX...
artifacts:
  files:
    - '**/*'
